### ISSUE TITLE
terminal can't show anything after I run python3 ./test.py

### ISSUE THREAD

**Issue by xubenji** [HNYuuu/SeeWasm#101]
I installed pure ubuntu20.04 and installed all requirements packages including wabt. When I run python3 test.py in the terminal I can't see any success info. Is it normal?

<img width="833" alt="截屏2024-01-06 下午5 31 34" src="https://github.com/HNYuuu/SeeWasm/assets/33605135/dae0ec51-234c-49b5-b0f8-283b4d22be05">

**Comment by HNYuuu** [comment]
Hi there. Sorry for the confusion. Actually we have updated the test.py file, and there will not be explicit log output if everything is OK. We will update the readme later.
