### ISSUE TITLE
errors in test, please check the screen shot

### ISSUE THREAD

**Issue by marapapman** [HNYuuu/SeeWasm#94]
![image](https://user-images.githubusercontent.com/5522358/220561955-3b299266-7029-40a6-81c6-3e75d2ef3cee.png)
![image](https://user-images.githubusercontent.com/5522358/220562102-ee1fd37e-3d1c-4953-b76c-51ad7986f610.png)

**Comment by HNYuuu** [comment]
It seems like you do not install all libraries correctly. Have you tried to install libraries through the following command?

```
python -m pip install -r requirements.txt
```
